[settings]
idiomatic_version_file_enable_tools = ["python", "ruby"]
experimental = true

[tools]
age = "latest"
claude = "latest"
docker-compose = "latest"
node = "lts"
sops = "latest"
docker-cli = "latest"
go = "1.25.1"
