[settings]
idiomatic_version_file_enable_tools = ["python", "ruby"]
experimental = true

[tools]
age = "latest"
claude = "latest"
docker-cli = "latest"
docker-compose = "latest"
go = "latest"
node = "lts"
bun = "latest"
python = "latest"
rust = "latest"
sops = "latest"
uv = "latest"
ripsecrets = "latest"
